### ISSUE TITLE
Error Code : 1113 , Error Name : SessionPublisherNotFound , Error Message : (null description)

### ISSUE THREAD

**Issue by ankitgupta394** [opentok/accelerator-core-android#106]
Hi Team, 

I am using Opentok in Android  for video calling & chat. My app was working fine before 7 days. But from last 7 days we are not able to connect session in Android. we are continuously getting Publisher not found or Camerafailed exception. 

Android studio version : 4.0.1

![opentok3](https://user-images.githubusercontent.com/17039214/94439532-29b3df00-01be-11eb-90ca-6e5ec14e6b3e.png)
    
![error for opentok2](https://user-images.githubusercontent.com/17039214/94439561-346e7400-01be-11eb-956a-e2e8ee8d6545.png)

![error for opentok](https://user-images.githubusercontent.com/17039214/94439589-3b958200-01be-11eb-84f3-3c97a56ce4cf.png)

Please tell any solution ASAP

Thanks

**Comment by igorwojda** [comment]
We are working on the fix. This is the bug in new releasee `1.0.23`. Please revert to `v1.0.22` for now.
`implementation 'com.opentok.android:opentok-accelerator-core:1.0.23'`

**Comment by ankitgupta394** [comment]
I am also not able to connect with 1.0.22. 

Our dependencies is:

    implementation 'com.opentok.android:opentok-accelerator-core:1.0.22'
    implementation 'com.opentok.android:opentok-accelerator-annotation:1.0.3'
    implementation 'com.opentok.android:opentok-accelerator-textchat:1.0.6'
    implementation 'com.opentok.android:opentok-android-sdk:2.16.5'

Android Studio Version is 4.0.1

Please tell any change we need to do on project. But it was working fine last week. I am continuously getting blank screen

**Comment by igorwojda** [comment]
1. We heave released `1.0.24` - This introduces the fix for number of participants and CameraFailed mentioned above. Please test it (make sure to run clean build after updating library).

2. You don't need this dependency, because `opentok-accelerator-core` depends on it (in fact it depends on newer version)
`implementation 'com.opentok.android:opentok-android-sdk:2.16.5'`

**Comment by ankitgupta394** [comment]
Thanks for your reply.

Now we are able to connect session with  accelerator-core v1.0.24.

**Comment by igorwojda** [comment]
Fixed by 
https://github.com/opentok/accelerator-core-android/pull/107
