### ISSUE TITLE
Android OTWrapper class constructor crahses

### ISSUE THREAD

**Issue by Hamzali** [opentok/accelerator-core-android#64]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.0.11
- iOS/Android/Browser version(s): Android 4.4
- Devices/Simulators/Machine affected: Simulator
- Reproducible in the demo project? (Yes/No):  Yes
- Related issues: None

#### Expected behavior

> OTWrapper constructor must create an instance.

#### Actual behavior

> In constructor, it goes to initAnalytics function and in this function;
``` String source = mContext.getPackageName(); ```
while running this line program crashes because mContext is null.

#### Steps to reproduce

> Just create an instance of OTWrapper class.

#### Crash log? Screenshots? Videos? Sample project?

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                                at com.tokbox.android.otsdkwrapper.wrapper.OTWrapper.initAnalytics(OTWrapper.java:1034)
                                                                                at com.tokbox.android.otsdkwrapper.wrapper.OTWrapper.<init>(OTWrapper.java:117)

**Comment by marinaserranomontes** [comment]
Thanks @Hamzali. It should be fixed in the last build: 1.0.13.
