### ISSUE TITLE
Error:Could not find any matches for com.opentok.android:opentok-accelerator-core:1.0.+ as no versions of com.opentok.android:opentok-accelerator-core are available. 

### ISSUE THREAD

**Issue by ABhayBohra** [opentok/accelerator-core-android#75]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by marinaserranomontes** [comment]
Hi ABhayBohra,

Thanks for the feedback. 
We are investigating the issue with Bintray.
Customers will currently have issues with all the OpenTok Android libs in the Maven repository.
As soon as we have an update, we’ll share it with you.

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @ABhayBohra ,

You could use "maven { url 'https://tokbox-telefonica.bintray.com/maven' }". It should work.

Best,
Marina

**Comment by ABhayBohra** [comment]
Thank you it worked..

**Comment by marinaserranomontes** [comment]
@ABhayBohra  Please keep in mind that this URL has been temporarily changed, we will keep you updated if there are any more changes.

**Comment by marinaserranomontes** [comment]
@ABhayBohra the following URL has been restored: https://tokbox.bintray.com/maven/
