### ISSUE TITLE
Failed to resolve: com.opentok.android:opentok-android-sdk:2.12.0

### ISSUE THREAD

**Issue by alperenbabagil** [opentok/accelerator-core-android#76]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> Compile project

#### Actual behavior

> Failed to resolve project

#### Steps to reproduce

> add opentok lib to project as suggested and try to compile

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by marinaserranomontes** [comment]
Hi alperenbabagil,

Thanks for the feedback. 
We are investigating the issue with Bintray.
Customers will currently have issues with all the OpenTok Android libs in the Maven repository.
As soon as we have an update, we’ll share it with you.

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @alperenbabagil,

You could use "maven { url 'https://tokbox-telefonica.bintray.com/maven' }". It should work.

Best,
Marina

**Comment by alperenbabagil** [comment]
Thanks @marinaserranomontes. It's working now.

**Comment by marinaserranomontes** [comment]
@alperenbabagil  Please keep in mind that this URL has been temporarily changed, we will keep you updated if there are any more changes.

**Comment by msach22** [comment]
@alperenbabagil the following URL has been restored: https://tokbox.bintray.com/maven/

**Comment by cppgarbagecollector** [comment]
please can any one tell me is OpenTok Accelerator can be user with the Normal Native WebRTC without TokBox gets into the equation and "if yes it can be used" is it free.
