### ISSUE TITLE
Loud noise starts coming when new remote joined

### ISSUE THREAD

**Issue by ABhayBohra** [opentok/accelerator-core-android#77]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by marinaserranomontes** [comment]
Hi @ABhayBohra,

I am not able to reproduce it. Please, could you clarify if you are using the accelerator-core-android and what is the remote side? web? android?iOS? etc.

Best,
Marina

**Comment by ABhayBohra** [comment]
Remote side means another android device which connects through video call.when session create successful, noise starts

**Comment by msach22** [comment]
Hey @ABhayBohra are you still seeing the noise issue when another user joins using an android device?

**Comment by ABhayBohra** [comment]
Yes..but when two devices are closer to each other

**Comment by msach22** [comment]
@ABhayBohra If your second device is in close proximity, you're most likely hearing feedback noise.
