### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by alperenbabagil** [opentok/accelerator-core-android#82]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.0.+
- iOS/Android/Browser version(s): Android target sdk 27
- Devices/Simulators/Machine affected: All devices
- Reproducible in the demo project? (Yes/No):  Yes
- Related issues: 

## Bug report

When I compile my project I'm getting this error:
Error:(28, 20) Failed to resolve: com.opentok.android:opentok-accelerator-core:1.0.+

I get this error with logging library too

#### Expected behavior

> ... To be compiled

#### Actual behavior

> ... Giving error 

#### Steps to reproduce

> ... Just try the sync gradle file

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by marinaserranomontes** [comment]
hi @alperenbabagil ,

Please, could you verify you have added in the build.gradle for your project the following line? It should be added to the allprojects/repositories section:

maven { url "http://tokbox.bintray.com/maven" }

Best,
Marina

**Comment by alperenbabagil** [comment]
I solved my problem. Thanks
