### ISSUE TITLE
Crash of app when not sending the data in TYPE field of open tok playground

### ISSUE THREAD

**Issue by parmarravi** [opentok/accelerator-core-android#86]
### General information

- Library version(s):1.0.21
- iOS/Android/Browser version(s): ANDROID
- Devices/Simulators/Machine affected: DEVICES
- Reproducible in the demo project? (Yes/No): Yes

#### Expected behavior

> The app should not get kill from any type of issue that's happening from the server.

#### Actual behavior

> Crash of app when not sending the data in **TYPE** field of open tok playground

#### Steps to reproduce

> Step 1  .  Connect a session from android app using accelerator-core-android library 
> Step 2  .  On TokBox playground server connect the session .
> Step 3  .  Send The Single message from the dashboard without adding any data in **TYPE**   field 
> Step 4  .  Check the app that was running ,the app has been crashed .    

 Crash log

> 2019-01-29 11:01:21.045 23001-23001/com.example.app E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
>         at java.util.Hashtable.get(Hashtable.java:365)
>         at com.tokbox.android.otsdkwrapper.wrapper.OTAcceleratorSession.dispatchSignal(OTAcceleratorSession.java:223)
>         at com.tokbox.android.otsdkwrapper.wrapper.OTAcceleratorSession.access$200(OTAcceleratorSession.java:25)
>         at com.tokbox.android.otsdkwrapper.wrapper.OTAcceleratorSession$4.onSignalReceived(OTAcceleratorSession.java:264)
>         at com.opentok.android.Session.onSignalReceived(Session.java:1790)
>         at com.opentok.android.Session$11.run(Session.java:1771)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6626)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by igorwojda** [comment]
PR https://github.com/opentok/accelerator-core-android/pull/100

**Comment by igorwojda** [comment]
It took us a while, but we are on it.
BTW This is a very good Bug @parmarravi 👍 Thank you for reporting
