### ISSUE TITLE
Setting Proguard issue with library 

### ISSUE THREAD

**Issue by parmarravi** [opentok/accelerator-core-android#87]
## New issue checklist

- [x]  I have read all of the [`README`](../README.md) 
- [X] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):1.0.21
- iOS/Android/Browser version(s):Android
- Devices/Simulators/Machine affected:Devices
- Reproducible in the demo project? (Yes/No):  Yes
- Related issues:

#### Expected behavior

> The app should run  with proguard rules 

#### Actual behavior

> App getting crash when the Proguard is enable with following code

>  -keep class com.opentok.** { *; }
>  -dontwarn com.opentok.**
>  -dontwarn org.codehaus.jackson.map.ext.**
> 

**GRADLE file** 

```
    implementation 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'
    implementation 'com.opentok.android:opentok-accelerator-core:1.0.21'
    implementation 'com.opentok.android:opentok-accelerator-annotation:1.0.1'
```

#### Steps to reproduce

> Enable ProGuard and run the app 

#### Crash log? Screenshots? Videos? Sample project?

>

>  java.lang.NoSuchFieldError: No static field PUBLIC_ONLY of type Lorg/codehaus/jackson/a/d$a; in class Lorg/codehaus/jackson/a/d$a; or its superclasses (declaration of 'org.codehaus.jackson.a.d$a' appears in /data/app/com.example.app-0UQOjKsC23lUqgHZvfvZsA==/base.apk!classes2.dex)
>         at java.lang.Class.getDeclaredAnnotation(Native Method)
>         at java.lang.Class.getAnnotation(Class.java:2481)
>         at org.codehaus.jackson.map.d.s$a.<clinit>(VisibilityChecker.java:178)
>         at org.codehaus.jackson.map.d.s$a.a(VisibilityChecker.java:186)
>         at org.codehaus.jackson.map.w.<clinit>(ObjectMapper.java:196)
>         at com.tokbox.android.a.a.<init>(OTKAnalytics.java:28)
>         at com.tokbox.android.otsdkwrapper.d.b.p(OTWrapper.java:1040)
>         at com.tokbox.android.otsdkwrapper.d.b.<init>(OTWrapper.java:123)

## Question or Feature Request

> ...

**Comment by EslamHussein** [comment]
@parmarravi  Did you find a solution for this issue?

**Comment by parmarravi** [comment]
Yes . Check the proguard rules. 

-keep class com.tokbox.android.** { *; }
-keep class com.opentok.android.** { *; }
-keep class org.codehaus.jackson.** { *; }
-keep class org.webrtc.** { *; }

-dontwarn com.opentok.android.**
-dontwarn com.tokbox.android.**
-dontwarn org.codehaus.jackson.**
