### ISSUE TITLE
Update SDK version

### ISSUE THREAD

**Issue by guness** [opentok/accelerator-core-android#89]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): latest
- iOS/Android/Browser version(s): latest
- Devices/Simulators/Machine affected: all new google play releases
- Reproducible in the demo project? (Yes/No):  does not matter
- Related issues:

## Bug report
Please update ext.sdkVersion to more recent one (2.15 or 2.16). Because otherwise we will not be able to publish a release on play store due to new 64bit requirement.

**Comment by marinaserranomontes** [comment]
Hi @guness ,

FYI, the sdk version has been updated.

Best,
Marina

**Comment by guness** [comment]
sorry, we are not using accelerator anymore, we have migrated to use opentok without this.
